name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 3:21
    - cron: '21 3 * * *'

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        python-version:
          - 2.7
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Display platform version
        run: python -c "import platform; print(platform.platform())"

      - name: Install Python packages
        run: |
          pip install --upgrade codecov tox setuptools
          pip install .
          pip list

      - name: Display tool versions
        run: python misc/build_helpers/show-tool-versions.py

      - name: Run tox
        run: tox -e py27,py27-coverage,pyinstaller
